"""empty message

Revision ID: 21a9a683f2ed
Revises: 
Create Date: 2022-05-05 22:58:55.200652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a9a683f2ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('lock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'lock')
    # ### end Alembic commands ###
